name: habbit_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  drift: ^2.3.0
  sqlite3_flutter_libs: ^0.5.12
  path_provider: ^2.0.11
  path: ^1.8.2
  sidebarx: ^0.14.0
  date_picker_timeline: ^1.2.3
  google_fonts: ^3.0.1
  flutter_share: ^2.0.0
  flutter_switch: ^0.3.2
  flutter_time_picker_spinner: ^2.0.0
  numberpicker: ^2.1.1
  file_picker: ^5.2.5
  table_calendar: ^3.0.8
  fl_chart: ^0.55.2
  pie_chart: ^5.3.2
  app_settings: ^4.1.8
  flutter_ringtone_player: ^3.2.0
  day_night_time_picker: ^1.1.3
  shared_preferences: ^2.0.15
  flutter_shake_animated: ^0.0.5
  circular_countdown_timer: ^0.2.3
  local_auth: ^2.1.3
  lottie: ^2.1.0
  url_launcher: ^6.1.7
  intl:
  awesome_notifications: ^0.7.4+1
  flutter_slidable: ^2.0.0
  permission_handler: ^10.2.0
  flutter_downloader: ^1.10.1
  # flowder: ^0.2.0
  vibration: ^1.7.6
  weekly_date_picker: ^1.3.0
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.2
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.4
  firebase_core: ^2.4.1
  firebase_storage: ^11.2.1
  googleapis: ^10.0.0
  googleapis_auth: ^1.3.1
  flutter_secure_storage: ^7.0.1
  screenshot: ^1.3.0
  share_plus: ^6.3.0
  share_files_and_screenshot_widgets_plus: ^1.0.4
  # vibration: ^1.7.6
  in_app_purchase: ^3.1.7

  cupertino_icons: ^1.0.2
  flutter_alarm_clock: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.3.3
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/my_database.db
