// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8wKaddd9AXsKZNLpRsZcvj-lakvDfZYw',
    appId: '1:9591880827:android:7dcedc1804e24e5a00b6de',
    messagingSenderId: '9591880827',
    projectId: 'plannerize-83ddd',
    storageBucket: 'plannerize-83ddd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNZppTRIl5v1OIaFXuQ5MVRePKRERppSU',
    appId: '1:9591880827:ios:d00f5df343ad95d200b6de',
    messagingSenderId: '9591880827',
    projectId: 'plannerize-83ddd',
    storageBucket: 'plannerize-83ddd.appspot.com',
    androidClientId: '9591880827-d7rjtl49utrlfp72bsk4jcdkaoips0fh.apps.googleusercontent.com',
    iosClientId: '9591880827-rav4js0k0dt9cmrcfdug3qvv5i0ev1me.apps.googleusercontent.com',
    iosBundleId: 'com.plannerize.app',
  );
}
